# PyTorch training of ResNet50 on ImageNet dataset

# Specify the Singularity image to use
+SingularityImage = "osdf:///ospool/uc-shared/public/OSG-Staff/pytorch-2.1.1.sif"

# Set the log, error, and output files with unique identifiers
log = en.$(Cluster).log.txt
error = en.$(Cluster).$(Process).err.txt
output = en.$(Cluster).$(Process).out.txt

# Set the executable to run
executable = en_val.sh
arguments = $(Process)

# Transfer main script and data
transfer_input_files = ensemble_val.py, subset_model1.pt, subset_model2.pt, subset_model3.pt, subset_model4.pt, subset_model5.pt

# Specify file transfer options
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# We require a machine with a compatible version of the CUDA driver
require_gpus = (DriverVersion >= 10.1)

# Request resources
request_cpus = 6
request_gpus = 1
request_memory = 20GB
request_disk = 100GB

# Queue the job for each submission
queue 1


